CREATE TABLE IF NOT EXISTS id_detail ( 
	id INT NOT NULL AUTO_INCREMENT,
	minor_id_no_en TEXT COLLATE utf8mb4_unicode_ci NOT NULL, 
	minor_id_no_ne TEXT COLLATE utf8mb4_unicode_ci NOT NULL,
	name_surname_en TEXT COLLATE utf8mb4_unicode_ci NOT NULL,
	name_surname_ne TEXT COLLATE utf8mb4_unicode_ci NOT NULL,
	gender TEXT NOT NULL,
	name_surname_father_en TEXT COLLATE utf8mb4_unicode_ci NOT NULL,
	name_surname_father_ne TEXT COLLATE utf8mb4_unicode_ci NOT NULL,
	address_father_en TEXT COLLATE utf8mb4_unicode_ci NOT NULL,
	address_father_ne TEXT COLLATE utf8mb4_unicode_ci NOT NULL,
	name_surname_mother_en TEXT COLLATE utf8mb4_unicode_ci NOT NULL,
	name_surname_mother_ne TEXT COLLATE utf8mb4_unicode_ci NOT NULL,
	address_mother_en TEXT COLLATE utf8mb4_unicode_ci NOT NULL,
	address_mother_ne TEXT COLLATE utf8mb4_unicode_ci NOT NULL,
	ctzn_en TEXT COLLATE utf8mb4_unicode_ci NOT NULL,
	ctzn_ne TEXT COLLATE utf8mb4_unicode_ci NOT NULL,
	name_add_guardian_en TEXT COLLATE utf8mb4_unicode_ci NOT NULL,
	name_add_guardian_ne TEXT COLLATE utf8mb4_unicode_ci NOT NULL,
	birth_date_en TEXT COLLATE utf8mb4_unicode_ci NOT NULL,
	birth_date_ne TEXT COLLATE utf8mb4_unicode_ci NOT NULL,
	birth_place_en TEXT COLLATE utf8mb4_unicode_ci NOT NULL,
	birth_place_ne TEXT COLLATE utf8mb4_unicode_ci NOT NULL,
	birth_muni INT NOT NULL,
	birth_ward INT NOT NULL,
	place_en TEXT COLLATE utf8mb4_unicode_ci NOT NULL,
	place_ne TEXT COLLATE utf8mb4_unicode_ci NOT NULL,
	muni INT NOT NULL,
	ward INT NOT NULL,
	officer_name_en TEXT COLLATE utf8mb4_unicode_ci NOT NULL,
	officer_pos_en TEXT COLLATE utf8mb4_unicode_ci NOT NULL,
	officer_name_ne TEXT COLLATE utf8mb4_unicode_ci NOT NULL,
	officer_pos_ne TEXT COLLATE utf8mb4_unicode_ci NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (birth_muni) REFERENCES local_level(id),
	FOREIGN KEY (muni) REFERENCES local_level(id)
) CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
